### ISSUE TITLE
error in preimage example?

### ISSUE THREAD

**Issue by tshabs** [matter-labs/zinc#1]
Hi,

While playing around with preimage example, I noticed that the `preimage_bits` is being right padded.  Shouldn't `preimage_bits` be reversed before padding, and then reversed again before hashing? (or am I misunderstanding something?)

E.g:

```
    let preimage_bits: [bool; FIELD_SIZE] = to_bits(preimage);
    let preimage_bits_reversed: [bool; FIELD_SIZE] = reverse(preimage_bits);
    let preimage_bits_padded: [bool; FIELD_SIZE_PADDED] = pad(preimage_bits_reversed, 256, false);
    let preimage_bits_padded_rereversed: [bool; FIELD_SIZE_PADDED] = reverse(preimage_bits_padded);
    let sha256_digest = sha256(preimage_bits_padded_rereversed);
```

I'd be happy to submit a PR.

Thanks, zinc is awesome !

**Comment by hedgar2017** [comment]
@tshabs hi! Sorry for the late reply!
I think your remark makes perfect sense. The example will be fixed in the next version of Zinc!
