### ISSUE TITLE
zinc_types not compiling

### ISSUE THREAD

**Issue by ReggieRumsfeld** [matter-labs/zinc#10]
I faced two issues compiling zinc_types:

- The "Serde" Feature is currently not enabled on/for num_old, which leads to issues with the fee and transaction type.

- transaction/mod.rs: 
 In the try_to_msg method a BigUint based on the newer num crate is used as input for the Msg::new() method, which expects a num_old BigUint.

The commits both reflect these issues:
https://github.com/ReggieRumsfeld/zinc

**Comment by hedgar2017** [comment]
This code has been removed in our development branches.
However, `development` and `master` branch `HEAD`s should be buildable using Rust 1.50
