### ISSUE TITLE
use ORM for zandbox::database

### ISSUE THREAD

**Issue by HAOYUatHZ** [matter-labs/zinc#2]
The CURD codes in https://github.com/matter-labs/zinc/blob/master/zandbox/src/database/client.rs and https://github.com/matter-labs/zinc/tree/master/zandbox/src/database/model are tedious and mantainence-unfriendly.

I think we can try using ORM (for example, https://github.com/diesel-rs/diesel)?

**Comment by hedgar2017** [comment]
@HAOYUatHZ we are moving away from diesel, as we don't find it convenient enough.
The code you mentioned above is more like a prototype and will be definitely refactored (not with diesel, though).

**Comment by HAOYUatHZ** [comment]
> @HAOYUatHZ we are moving away from diesel, as we don't find it convenient enough.
> The code you mentioned above is more like a prototype and will be definitely refactored (not with diesel, though).

Thanks for your clarification!
