### ISSUE TITLE
Transactions batch summary fee is too low

### ISSUE THREAD

**Issue by z330789559** [matter-labs/zinc#5]
this git  reps https://github.com/z330789559/simplepriceoracle/tree/dev

i writer a mut mthod to update contract data, config is same with git resp dev branch
 when run zargo call --address 0xbabcaa8c0cda92e40074e0e39bdd69977e9c61f9 --network rinkeby --method update 
     Calling method `update` of the contract `SimplePriceOracle v0.1.7` with address 0xbabcaa8c0cda92e40074e0e39bdd69977e9c61f9 on network `rinkeby`
[ERROR zargo] contract calling request: HTTP error (500 Internal Server Error) ZkSync: RpcError(Failure { jsonrpc: Some(V2), error: Error { code: ServerError(104), message: "Transactions batch summary fee is too low", data: None }, id: Str("1") })     

how to  preduce private_key file ? it's content must be 0 or 1?

**Comment by hedgar2017** [comment]
The private_key file must contain the private key of your zkSync account you are make transfers from.
Without preceding `0x`.
It should match `msg.sender`, but afair it is not checked for now.

**Comment by z330789559** [comment]
@hedgar2017 
input.json msg.sender
  "msg": {
    "sender": "0xDF255110565ffF30cB72dfd4b372Ce2C4b1fd32a",
    "recipient": "0x4c1Af8a707541F860987E643437b918B26AB4376",
    "token_address": "0x3b00ef435fa4fcff5c209a37d1f3dcff37c705ad",
    "amount": "177400000000000"
  },
is it ok? , need to remove 0x?  
private_key is 1000100000000000000000000000000000000000000000000000000000000011
, it's public key is 0xDF255110565ffF30cB72dfd4b372Ce2C4b1fd32a ,but it has eth

**Comment by hedgar2017** [comment]
`input.json` is ok.
Are you sure your private key is `1000100000000000000000000000000000000000000000000000000000000011`.
Did you create it manually?

**Comment by z330789559** [comment]
@hedgar2017 yes ,i  create it manually,  after create ,i generate public ,you can try  my project ,All information is on git project

**Comment by z330789559** [comment]
i want to known that how to create private key ,  i want to known how to I want to know how to call another contract from one contract inside the testnet contract ， how to code for implementing  the funtion

**Comment by hedgar2017** [comment]
I see.
An update has been done on `rinkeby` this morning.
I'll talk with the guys and ask what has changed related to fees.

**Comment by hedgar2017** [comment]
@z330789559 to call another contract, load it with `Contract::fetch(<address>)` and call one of its methods.

**Comment by hedgar2017** [comment]
https://zinc.zksync.io/07-smart-contracts/01-storage-and-methods.html#fetch

**Comment by z330789559** [comment]
@hedgar2017  Very awesome, I have verified it,

**Comment by hedgar2017** [comment]
@z330789559 as for the fee issue, devs say that you must have been requested fee before the update and sent the transaction after it.
Please, try some more transactions and let me know.

**Comment by z330789559** [comment]
how  to requested fee ?

**Comment by hedgar2017** [comment]
@z330789559 ah, `zargo` does that automatically.
