### ISSUE TITLE
contract::fetch error!!

### ISSUE THREAD

**Issue by z330789559** [matter-labs/zinc#6]
in rinkeby 
Ctoken contract   address 0x7be2b193f09f5861314a08853f31ff4da4a1a8c
SimplePriceOracle contract  address 0xfcba0cc77db8f135f0c9fe864316ef9b98e3a3ba

zargo query --address 0xfcba0cc77db8f135f0c9fe864316ef9b98e3a3ba --network rinkeby
result
{
  "address": "0xfcba0cc77db8f135f0c9fe864316ef9b98e3a3ba",
  "balances": [
    {
      "key": "0x0",
      "value": "17620000000000"
    }
  ],
  "ctoken": "0x7be2b193f09f5861314a08853f31ff4da4a1a8c"
}
call contract method:

  pub fn getAddress(self)->u248{
       let instance =  Ctoken::fetch(self.ctoken);
          instance.value
    }
instance is Ctoken  code follow
contract Ctoken {
   pub value:u248;
    pub fn new(_value:u248) -> Self {
        Self {
            value:_value
        }
    }
    pub fn get(self)->u248{
     self.value
    }
    pub fn update(mut self,amout :u248){
      let  tem=add(self.value,amout);
          self.value=tem;
    }
}

run zargo query --address 0x1c082d9cec55658187ba63519672c9d19f15041b --network rinkeby --method  getAddress
error
contract querying request: HTTP error (502 Bad Gateway) <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>

contract code can download by  zargo download

**Comment by hedgar2017** [comment]
@z330789559 hi. It is a network problem, unrelated to `zargo` or contracts.
Btw, are you using version 0.2.0 or 0.2.1?

**Comment by z330789559** [comment]
@hedgar2017  0.2.1 query or call both report errors like this

**Comment by hedgar2017** [comment]
@z330789559 I still don't understand what are the exact conditions of this error.
Bad Gateway means that Zandbox server is unreachable for you.
There are a lot of possible causes, but most likely it is your network issue.

Please, provide more info on the error conditions and frequency.

**Comment by z330789559** [comment]
Bad 502 looks more like the request has been sent to zKserver, but their service does not exist. I just use the command zargo query - address 0 x1c082d9cec55658187ba63519672c9d19f15041b - network rinkeby - method which getAddress here logic should be zargo will go to call the server interface found query server does not exist, however, Inside this the main reason is within 0 x1c082d9cec55658187ba63519672c9d19f15041b contracts call < cONTRACT > : : FETCH method, I think this method

**Comment by z330789559** [comment]
zargo query - address 0 x1c082d9cec55658187ba63519672c9d19f15041b - network rinkeby - method  getAddress   i  will exec this command with RPC  to proof the skzerver can work

**Comment by hedgar2017** [comment]
@z330789559 ok, thanks!
I'll check the Contract::fetch method.
However, many people used it and it seemed to work.
