### ISSUE TITLE
a smart contract example to make zksync transfer

### ISSUE THREAD

**Issue by jackzhp** [matter-labs/zinc#8]
for the zinc smart contract, we have 2 examples in the documents.
I would like to see a smart contract which is able to make a zksync transfer when a condition is met.

The condition, for example, to be provide a piece of data whose sha256 is the target value. When this condition is met, then a zksync transfer is executed.

Can someone please help to put such an example in the document?

Or even better, if all the transfer related address/account information could be hidden.

Jack

**Comment by hedgar2017** [comment]
In Zinc 0.2.3, you may just enclose the `zksync::transfer` call with a conditional `if`.
On the other features, please, follow our Turing-complete release roadmap.
